run:
  tests: false
linters:
  enable-all: true
  disable:
    # complexity
    - gocognit
    - gocyclo
    - cyclop
    - maintidx
    # disabled
    - godot
    - depguard
    - dupl
    - ireturn
    - recvcheck
    - varnamelen
    - exhaustruct
    - tagliatelle
    - wrapcheck
    - paralleltest
    - funlen
    - gochecknoglobals
    - tagalign
    - gosimple
    - errname
    - nestif
    - dogsled
    - inamedparam
    - gomnd
    - err113
    - mnd
linters-settings:
  misspell:
    locale: US
